using System;


/// <summary>
/// TODO: Comment about the program
/// 
/// Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
/// By starting with 1 and 2, the first 10 terms will be:
///     1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
/// 
/// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
/// 
/// </summary>
namespace Eular_Problem_2
{
    class Program
    {
        static void Main(string[] args)
        {
            int numberOfResponses = 10;
//            int response = new int[numberOfResponses];

            for (int x  = 1; x < numberOfResponses; x++)
            {


                // THIS ONE DOES NOT FUNCTION YET
                Console.WriteLine(x);
//                response[x] = response[x - 1] + response[x - 2];
            }
            Console.WriteLine("Even Fibonancci Numbers Problem 2");
        }
    }
}
